default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: ~
  port: 5432
  host: localhost
  pool: 5
  allow_concurrency: true
  min_messages: error

development:
  <<: *default
  database: bzwbk_development

test:
  <<: *default
  database: bzwbk_test

production:
  <<: *default
  database: bzwbk_production
  username:
  password:
